import {
	Box,
	Divider,
	Stack,
	StackDivider,
	Text,
	useColorModeValue as mode,
	Badge,
	Button,
} from "@chakra-ui/react";
import { FaMobileAlt, FaShieldAlt } from "react-icons/fa";
import type React from "react";

const AddressSection = () => (
	<Box maxW={{ base: "xl", md: "7xl" }} mx="auto">
		<Box
			rounded={{ lg: "lg" }}
			bg={mode("white", "gray.700")}
			maxW="3xl"
			mx="auto"
			shadow="base"
			overflow="hidden"
		>
			<Box px="6" py="4">
				<Text as="h3" fontWeight="bold" fontSize="lg">
					Verification options
				</Text>
				<Text color={mode("gray.600", "gray.300")} fontSize="sm">
					Add an extra layer of security to block unauthorized access and
					protect your account.
				</Text>
			</Box>
			<Divider />
			<Stack spacing="6" divider={<StackDivider />} py="5" px="8">
				<Address isRecommended title="Authenticator" icon={<FaShieldAlt />}>
					Enter a code generated by your authenticator app to confirm it’s you.
				</Address>
				<Address title="Mobile app prompt" icon={<FaMobileAlt />}>
					Receive a prompt from your mobile app to confirm it’s you.
				</Address>
			</Stack>
		</Box>
	</Box>
);

export default AddressSection;

interface AddressProps {
	icon: React.ReactElement;
	title: string;
	children: React.ReactNode;
	isRecommended?: boolean;
	onClickEnable?: React.MouseEventHandler;
}

export const Address = (props: AddressProps) => {
	const { title, children, icon, isRecommended, onClickEnable } = props;
	return (
		<Stack
			direction={{ base: "column", sm: "row" }}
			spacing="5"
			justify="space-between"
			pos="relative"
		>
			<Stack
				direction={{ base: "column", sm: "row" }}
				spacing="4"
				align="flex-start"
				flex="1"
			>
				<Box aria-hidden fontSize="2xl" pt="1" color="gray.500">
					{icon}
				</Box>
				<Box flex="1">
					<Box as="h4" fontWeight="bold" maxW="xl">
						<span>{title}</span>{" "}
						{isRecommended && <Badge marginStart="1">Recommended</Badge>}
					</Box>
					<Box
						maxW={{ base: "xs", md: "unset" }}
						color={mode("gray.600", "gray.400")}
						fontSize="sm"
					>
						{children}
					</Box>
				</Box>
			</Stack>
			<Button colorScheme="blue" onClick={onClickEnable}>
				Enable
			</Button>
		</Stack>
	);
};

Address.defaultProps = {
	isRecommended: false,
	onClickEnable: () => {},
};
