name: Deploy Backend

on:
  push:
    branches:
      - main

steps:
  - name: executing remote ssh commands using password
    uses: appleboy/ssh-action@v1.0.0
    with:
      host: "hamroapi.rudejellyfish.live"
      username: "azureuser"
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      script: dokku git:sync --build api https://github.com/sahrohit/fullstack-ecommmerce.git main
